// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc/interface.proto

package DISYS_HandIn4_Ben_Dover

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RicartAgrawalaService_RicartAgrawala_FullMethodName = "/RicartAgrawala.RicartAgrawalaService/RicartAgrawala"
)

// RicartAgrawalaServiceClient is the client API for RicartAgrawalaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaServiceClient interface {
	RicartAgrawala(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type ricartAgrawalaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaServiceClient(cc grpc.ClientConnInterface) RicartAgrawalaServiceClient {
	return &ricartAgrawalaServiceClient{cc}
}

func (c *ricartAgrawalaServiceClient) RicartAgrawala(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, RicartAgrawalaService_RicartAgrawala_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartAgrawalaServiceServer is the server API for RicartAgrawalaService service.
// All implementations must embed UnimplementedRicartAgrawalaServiceServer
// for forward compatibility
type RicartAgrawalaServiceServer interface {
	RicartAgrawala(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

// UnimplementedRicartAgrawalaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRicartAgrawalaServiceServer struct {
}

func (UnimplementedRicartAgrawalaServiceServer) RicartAgrawala(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RicartAgrawala not implemented")
}
func (UnimplementedRicartAgrawalaServiceServer) mustEmbedUnimplementedRicartAgrawalaServiceServer() {}

// UnsafeRicartAgrawalaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServiceServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServiceServer interface {
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

func RegisterRicartAgrawalaServiceServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServiceServer) {
	s.RegisterService(&RicartAgrawalaService_ServiceDesc, srv)
}

func _RicartAgrawalaService_RicartAgrawala_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServiceServer).RicartAgrawala(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartAgrawalaService_RicartAgrawala_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServiceServer).RicartAgrawala(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartAgrawalaService_ServiceDesc is the grpc.ServiceDesc for RicartAgrawalaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawalaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartAgrawala.RicartAgrawalaService",
	HandlerType: (*RicartAgrawalaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RicartAgrawala",
			Handler:    _RicartAgrawalaService_RicartAgrawala_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
